<a href="https://colab.research.google.com/github/Nicessly/Repositorio-de-Investigacion/blob/main/CodigoInvestigacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Matriz de calificaciones (usuarios x productos)
# 0 indica que no hay calificación
ratings = np.array([
    [5, 3, 0, 1],
    [4, 0, 0, 1],
    [1, 1, 0, 5],
    [0, 0, 5, 4],
    [1, 0, 4, 0]
])

# Aplicar SVD
U, sigma, VT = np.linalg.svd(ratings, full_matrices=False)

# Convertir sigma en matriz diagonal
sigma = np.diag(sigma)

# Reconstrucción aproximada de la matriz original
approx_ratings = np.dot(np.dot(U, sigma), VT)

print("Matriz original (0 indica sin calificar):")
print(ratings)

print("\nMatriz reconstruida (predicciones de calificaciones):")
print(np.round(approx_ratings, 2))

# Ejemplo: predicción para usuario 0, producto 2 (índice 0,2)
prediccion = approx_ratings[0, 2]
print(f"\nPredicción para el usuario 1 en el producto 3: {prediccion:.2f}")

Matriz original (0 indica sin calificar):
[[5 3 0 1]
 [4 0 0 1]
 [1 1 0 5]
 [0 0 5 4]
 [1 0 4 0]]

Matriz reconstruida (predicciones de calificaciones):
[[ 5.  3.  0.  1.]
 [ 4. -0.  0.  1.]
 [ 1.  1.  0.  5.]
 [ 0.  0.  5.  4.]
 [ 1.  0.  4. -0.]]

Predicción para el usuario 1 en el producto 3: 0.00
